    <ul id="avatars">
    	<li><a href=""><img src="images/avatars/ava1.jpg" /></a></li>
        <li><a href=""><img src="images/avatars/ava2.jpg" /></a></li>
        <li><a href=""><img src="images/avatars/ava3.jpg" /></a></li>
        <li><a href=""><img src="images/avatars/ava4.jpg" /></a></li>
        <li><a href=""><img src="images/avatars/ava5.jpg" /></a></li>
        <li><a href=""><img src="images/avatars/ava6.jpg" /></a></li>
        <li><a href=""><img src="images/avatars/ava7.jpg" /></a></li>
        <li><a href=""><img src="images/avatars/ava8.jpg" /></a></li>
        <div style="clear: both"></div>
        These ladies are on TPX, you should be too!
    </ul>
    
    <?php if(!$this->user){ ?>
    <a href="#" id="create-account">Create an Account</a>
    <? } ?>
    <div style="clear:both"></div>

    <div id="slideshow">
    
    <div id="slidesContainer">
        <div class="slide"><img src="images/slider/1.jpg" /></div>
        <div class="slide"><img src="images/slider/2.jpg" /></div>
        <div class="slide"><img src="images/slider/3.jpg" /></div>
    </div>
    
    <div id="slidesContainer2">
        <div class="slide2"><img src="images/slider/thumbs/1.jpg" /></div>
        <div class="slide2"><img src="images/slider/thumbs/2.jpg" /></div>
        <div class="slide2"><img src="images/slider/thumbs/3.jpg" /></div>     
    </div>
    
    <div id="slidesContainer3">
        <div class="slide3">
			<div class="slidesContainer3-bg"></div>
        	<div class="slide3-title">Guys Ask, Ladies Answer</div>
            <div class="slide3-desc">Learn</div>
        </div>  
        <div class="slide3">
    	    <div class="slidesContainer3-bg"></div>
        	<div class="slide3-title">Guys Ask, Ladies Answer 2</div>
            <div class="slide3-desc">Learn</div>
        </div> 
        <div class="slide3">
			<div class="slidesContainer3-bg"></div>
        	<div class="slide3-title">Guys Ask, Ladies Answer 3</div>
            <div class="slide3-desc">Learn</div>
        </div> 
    </div>
    
    </div><!-- #slideshow -->
    
    <div id="home-questions">
    	<div class="home-question-cont">
        	<div class="home-question-top">
            	Join the conversation...
                <div class="home-question-date">September 15, 2011</div>
            </div>
            <div class="home-question">Would you sell your panties if the money was going to a good cause?</div>
        </div>
        <div class="home-question-bottom">
        	<div class="home-question-stat">7<div class="home-question-stat-text">Comments</div></div>
            <div class="home-question-stat">26<div class="home-question-stat-text">Shared</div></div>
            <div class="home-question-stat home-question-stat-last">52%<div class="home-question-stat-text">Comments</div></div>
            <div class="home-question-answer">"YES"</div>
            <div class="home-question-tweet"><a href="https://twitter.com/share" class="twitter-share-button" data-count="horizontal">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script></div>
            <div class="home-question-facebook">
            	<div id="fb-root"></div>
				<script>(function(d, s, id) {
                  var js, fjs = d.getElementsByTagName(s)[0];
                  if (d.getElementById(id)) {return;}
                  js = d.createElement(s); js.id = id;
                  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
                  fjs.parentNode.insertBefore(js, fjs);
                }(document, 'script', 'facebook-jssdk'));</script>
                
                <div class="fb-like" data-send="false" data-layout="button_count" data-width="100" data-show-faces="false"></div>
            </div>
        </div>
    </div><!-- #home-questions -->
	
	<div id="questions-slideshow">
		<div class="leftcol">
			<ul>
				<li><div class="cat1"><h3>Barcode</h3><p>Learn the Lingo</p></div></li>
				<li><div class="cat2"><h3>The Frisky</h3><p>Dating / Sex</p></div></li>
				<li><div class="cat3"><h3>Man Craft</h3><p>Grooming / Style</p></div></li>
			</ul>
		</div>
		<div class="middlecol">
			<ul>
				<li class="cat1"><h3><span>Question:</span><p><strong>Does "I'm out" equal<br />"I'm trying to get laid"?</strong></p></h3><img src="images/layout/questions/barcode.jpg" /><div></div></li>
				<li class="cat2"><h3><span>Question:</span><p><strong>Would you sell your panties if the money was going to a good cause?</strong></p></h3><img src="images/layout/questions/frisky.jpg" /><div></div></li>
				<li class="cat3"><h3><span>Question:</span><p><strong>Are nerds the new rockstars or still just... nerds?</strong></p></h3><img src="images/layout/questions/mancraft.jpg" /><div></div></li>
			</ul>
		</div>
		<div class="rightcol">
			<ul>
				<li class="cat1">
					<div class="twitter-header">
						<p><a href="">@THEPANTYEXCHANGE</a></p>
						<h3>What She Said</h3>
					</div>
					<div class="tweet-cont">
						<div class="tweet">
							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc in molestie odio. With a link <a href="">http://tinyurl.com/5o77k</a>
							<div class="tweet-date">October 1, 2011</div>
						</div>
						<div class="tweeter"><a href="" target="_blank" class="tweeter-avatar"><img src="images/avatars/ava10.jpg" /></a> <a href="" target="_blank" class="tweeter-name">Kate</a></div>
					</div>
				</li>
				<li class="cat2">
					<div class="twitter-header">
						<p><a href="">@THEPANTYEXCHANGE</a></p>
						<h3>What She Said</h3>
					</div>
					<div class="tweet-cont">
						<div class="tweet">
							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc in molestie odio. With a link <a href="">http://tinyurl.com/5o77k</a>
							<div class="tweet-date">October 1, 2011</div>
						</div>
						<div class="tweeter"><a href="" target="_blank" class="tweeter-avatar"><img src="images/avatars/ava11.jpg" /></a> <a href="" target="_blank" class="tweeter-name">Linda</a></div>
					</div>
				</li>
				<li class="cat3">
					<div class="twitter-header">
						<p><a href="">@THEPANTYEXCHANGE</a></p>
						<h3>What She Said</h3>
					</div>
					<div class="tweet-cont">
						<div class="tweet">
							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc in molestie odio. With a link <a href="">http://tinyurl.com/5o77k</a>
							<div class="tweet-date">October 1, 2011</div>
						</div>
						<div class="tweeter"><a href="" target="_blank" class="tweeter-avatar"><img src="images/avatars/ava12.jpg" /></a> <a href="" target="_blank" class="tweeter-name">Victoria</a></div>
					</div>
				</li>
			</ul>
		</div>
	</div>