<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?php echo $this->title; ?></title>

<link href="/css/main.css" rel="stylesheet" type="text/css" />

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript" src="/js/cufon-yui.js"></script>
<script type="text/javascript" src="/js/HelveticaSTDBlackCondensed.js"></script>
<script type="text/javascript" src="/js/HelveticaSTDLightCondensed.js"></script>
<script type="text/javascript" src="/js/main.js"></script>
<script type="text/javascript" src="/js/slider.js"></script>
<script type="text/javascript" src="/js/openid-jquery.js"></script>
<script type="text/javascript" src="/js/openid-en.js"></script>
<script type="text/javascript" src="/js/jien.js"></script>
<script type="text/javascript" src="http://use.typekit.com/rcd0yyh.js"></script>
<script type="text/javascript">try{Typekit.load();}catch(e){}</script>
<script type="text/javascript" src="/themes/adventure/js/easing/jquery.easing.1.3.js"></script>
<script type="text/javascript" src="/themes/adventure/js/kwicks/jquery.kwicks-1.5.1.pack.js"></script>
<script type="text/javascript" src="/themes/adventure/js/swfobject/swfobject.js"></script>
<!-- plugins -->
<script src="/js/plugins/toastmessage/jquery.toastmessage.js" type="text/javascript"></script>
<link rel="stylesheet" href="/js/plugins/toastmessage/css/jquery.toastmessage.css">

<script type="text/javascript" src="http://fast.fonts.com/jsapi/4d3f295e-fe69-43e6-ad37-bfceb79a2f08.js"></script>

<script>
var twitter_id = "<?php echo TWITTER_ID; ?>";
var disqus_shortname = '<?php echo DISQUS_ID; ?>';
<?php if(APPLICATION_ENV != 'prod'){ ?>
var disqus_developer = 1;
<?php } ?>
</script>
<script>
$ = jQuery;
$(document).ready(function(){

<?php
$flash = $this->flashMessenger();
if($flash){
?>
	$.gritter.add({
		// (string | mandatory) the heading of the notification
		title: ' ',
		// (string | mandatory) the text inside the notification
		text: "<?php echo strip_tags(addslashes($flash)); ?>"
	});
	return false;
<?php } ?>
});
</script>

</head>

<body>

<div id="wrapper">

	<div id="header">
    	<a href="/" id="logo"></a>
        <div id="login"><?php if($this->user){ ?><a href="/user/logout">LOGOUT</a><? } else { ?><a href="/user/login">LOGIN/SIGNUP<? } ?>&nbsp;&nbsp;&nbsp;&nbsp;<a href="">HELP</a></div>
        <div id="menu">
        	<a href="">ABOUT</a><div class="menu-sep">/</div>
            <a href="/battle">BATTLE</a><div class="menu-sep">/</div>
            <a href="">LEARN</a><div class="menu-sep">/</div>
            <a href="">OUR LADIES</a>
        </div>
    </div>

	<?php
		echo $this->layout()->content;
	?>
	
    <div style="clear: both"></div>
    
    <div id="footer">
        <div id="footer-logo"></div>
    </div>
    
</div><!-- #wrapper -->
</div>
</div>

<script>
// login event
$(document).ready(function(){
	$('#user_login_show').click(function(e){
		$('.login_register_show').hide();
		$('.login_register').hide();
		$('#user_register_show').show();
		$('#user_login').show();
	});

	$('#user_register_show').click(function(e){
		$('.login_register_show').hide();
		$('.login_register').hide();
		$('#user_login_show').show();
		$('#user_register').show();
	});

});
</script>

<!--DISQUS-->
<script type="text/javascript">

/* * * DON'T EDIT BELOW THIS LINE * * */
(function () {
    var s = document.createElement('script'); s.async = true;
    s.type = 'text/javascript';
    s.src = 'http://' + disqus_shortname + '.disqus.com/count.js';
    (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script>

<script type="text/javascript">

/* * * DON'T EDIT BELOW THIS LINE * * */
(function () {
    var s = document.createElement('script'); s.async = true;
    s.type = 'text/javascript';
    s.src = 'http://' + disqus_shortname + '.disqus.com/count.js';
    (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script>

</body>
</html>
