			<!-- MAIN CONTAINER -->
			<div id="content">
				<div class="one">
					<!-- COLUMNS CONTAINER STARTS-->
					<div class="intro-pages">
						<!-- INTRO DIV STARTS-->
						<h3>Welcome to <span class="colored">Adventure</span>, Clean &amp; Simple <span class="colored">HTML5 </span> template.Feel free to browse through all the pages and see what's &quot;Adventure&quot; capable to do for You.Enjoy! </h3>
					</div>
					<!-- INTRO ENDS-->
				</div>
				<!-- COLUMNS CONTAINER ENDS-->
				<div class="one-fourth">
					<p>
						 Sit aliquip ipsa Invitamus me missam canticis Nuda dulcis natura puella ut a
					</p>
					<p>
						<strong>Our  offices</strong>
					</p>
					<p>
						 Guild of the Leather Apron<br/> 123 Main st. #123<br/> Los Angeles, CA, 91200 <br/>
					</p>
					<p>
						<strong>Contact Info</strong>
					</p>
					<p style="margin-bottom:0;">
						 T: 1 (213) 123-1234 <br/> F: 1 (213) 123-1234 <br/> E: <a href="mailto:jaequery@gmail.com">jaequery@gmail.com</a>
					</p>
				</div>
				<div class="inner-content last">
					<iframe width="710" height="220" src="http://maps.google.com/maps?f=d&amp;hl=en&amp;geocode=&amp;saddr=Perth&amp;daddr=-12.554564,130.869141+to:Bishop+Dr+%40-27.371780,+153.185980+to:Wanganderry+Rd+%40-34.310430,+150.262350+to:Unknown+road+%40-37.993930,+144.580460+to:Fremantle&amp;mrcr=0,1&amp;mrsp=1&amp;sz=4&amp;mra=dme&amp;sll=-24.20689,136.582031&amp;sspn=47.972215,66.708984&amp;ie=UTF8&amp;om=1&amp;s=AARTsJrOrTNCi3R5hglWCxsahY3qKUX7Ig&amp;ll=-24.20689,136.582031&amp;spn=46.989399,52.734375&amp;z=3&amp;output=embed">
					</iframe>
				</div>
				<!-- COLUMNS CONTAINER ENDS-->
				<div class="one">
					<div class="horizontal-line">
					</div>
					<div class="one-fourth">
						<ul class="simple-nav">
							<li><a href="about.html">About Us</a></li>
							<li><a href="about.html">News Archive</a></li>
							<li><a href="about.html">Our Services</a></li>
							<li><a href="about.html">Our Team</a></li>
							<li><a href="about.html">Clients Testimonials</a></li>
							<li><a href="jobs.html">Job Opportunities</a></li>
							<li><a href="about.html">F.A.Q</a></li>
							<li><a href="about.html">404 Error Page</a></li>
						</ul>
						<br/>
						<div class="pdf">
							<a href="#">Download our <br/> Services Brochure</a>
						</div>
					</div>
					<div class="inner-content last">
						<form action="/contact/add" id="contact-form" method="post">
							<fieldset>
								<label>Name <span class="required">*</span></label>
								<input type="text" name="name" id="Myname" value="" class="text requiredField"/>
							</fieldset>
							<fieldset>
								<label>Email <span class="required">*</span></label>
								<input type="text" name="email" id="myemail" value="" class="text requiredField email"/>
							</fieldset>
							<fieldset>
								<label>Subject <span class="required">*</span></label>
								<input type="text" name="subject" id="mySubject" value="" class="text requiredField subject"/>
							</fieldset>
							<fieldset>
								<label>Your Message <span class="required">*</span></label>
								<textarea name="message" id="Mymessage" rows="20" cols="30" class="text requiredField"></textarea>
							</fieldset>
							<fieldset>
								<input name="Mysubmitted" id="Mysubmitted" value="Send Message" class="button blue" type="submit"/>
							</fieldset>
						</form>
						<!--END form ID contact_form-->
					</div>
