	<link href="/css/battle.css" rel="stylesheet" type="text/css" />
	<script type="text/javascript" src="/js/battle.js"></script>
	
	<div id="left-sidebar">
	
		<div id="start-your-profile" class="widget">
			<h2>START YOUR PROFILE</h2>
			<div id="start-your-profile-go">GO</div>
		</div>
		
		<div id="battle-menu" class="widget">
			<ul>
				<li><span>All</span></li>
				<li><span>TPX Girls</span></li>
				<li><span>Champs</span></li>
				<li class="last"><span>Celebs</span></li>
			</ul>
		</div>
		
		<div id="battle-share-header" class="widget">
			<h2>Like battling? Share it with friends</h2>
		</div>
		<div id="battle-share" class="widget">
			<div class="tweet-button"><a href="https://twitter.com/share" class="twitter-share-button" data-count="horizontal">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script></div>
            <div class="facebook-button">
                <iframe src="//www.facebook.com/plugins/like.php?href&amp;send=false&amp;layout=button_count&amp;width=110&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font&amp;height=21&amp;appId=197559583651663" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:110px; height:21px;" allowTransparency="true"></iframe>
            </div><!-- .like-button -->
		</div>
		
		<div id="battle-filter" class="widget">
			<h2>What filters would you like</h2>
			<ul>
				<li>Location</li>
				<li>Education</li>
				<li class="hit">Style</li>
			</ul>
		</div>
	
	</div><!-- end #left-sidebar -->
	
	<div id="battle-toolbar">
		<div id="battle-desc">Presenting the TPX Battle</div>
		<div id="battle-viewing">View: 2 of 11 Ladies</div>
		<div id="battle-2view"></div>
		<div id="battle-6view"></div>
		<div id="battle-compare">COMPARE</div>
	</div>
	
	<div id="battle-girl1" class="battle-girl">
		<div class="battle-stats">
			<div class="battle-stat">7<div class="battle-stat-text">Likes</div></div>
			<div class="battle-stat">26<div class="battle-stat-text">Shared</div></div>
			<div class="battle-stat battle-stat-last">52%<div class="battle-stat-text">Click Rate</div></div>
		</div>
		<div class="battle-photo-cont">
			<div class="battle-photo">
				<img src="/images/layout/battle/battle_0.jpg" />
				<div class="battle-overlay"></div>
			</div>
			<div class="battle-user">
				<div class="battle-join-date">Joined TPX Aug. 10, 2011</div>
				<div class="battle-username">kate232</div>
				<div class="like-button battle-like-button"></div>
			</div>
		</div>
	</div>
	
	<div id="battle-girl2" class="battle-girl">
		<div class="battle-stats">
			<div class="battle-stat">10<div class="battle-stat-text">Likes</div></div>
			<div class="battle-stat">34<div class="battle-stat-text">Shared</div></div>
			<div class="battle-stat battle-stat-last">74%<div class="battle-stat-text">Click Rate</div></div>
		</div>
		<div class="battle-photo-cont">
			<div class="battle-photo">
				<img src="images/layout/battle/battle_1.jpg" />
				<div class="battle-overlay"></div>
			</div>
			<div class="battle-user">
				<div class="battle-join-date">Joined TPX Aug. 31, 2011</div>
				<div class="battle-username">hoty452</div>
				<div class="like-button battle-like-button"></div>
			</div>
		</div>
	</div>
	
	<div style="clear: both"></div>
