<script type="text/javascript">
    var imgPath = '<?php echo $this->baseUrl('images/');?>';
    jQuery(document).ready(function() {
        openid.img_path = imgPath;
        openid.init('openid_identifier');
        openid.setDemoMode(false); //Stops form submission for client javascript-only test purposes
    });
</script>

<div style="width:300px;padding-left:130px;float:left;height:500px;">
	<h4>Use your existing services</h4>
	<form action="<?php echo $this->baseUrl('/user/login');?>" method="get" id="openid_form">
		<p><a href="javascript:openid.signin('facebook');"><img src="/images/login/facebook.png"></a></p>
		<p><a href="javascript:openid.signin('twitter');"><img src="/images/login/twitter.png"></a></p><br/>
	</form>
</div>

<div style="color:#444;width:100px;float:left;font-size:24px;height:400px;padding-top:100px;text-align:left;font-weight:bold;">
	or
</div>

<div style="width:430px;float:left;height:500px;">
	
	<div id="user_login" class="hide login_register">
		<h4>Use your TPX account</h4>
		<form action="/auth/login" id="login_form" method="post">
			<input type="hidden" name="redir" value="/">
			<fieldset>
				<label>Email <span class="required">*</span></label>
				<input type="text" name="email" id="login_email" value="" class="text requiredField email" />
			</fieldset>
			<fieldset>
				<label>Password <span class="required">*</span></label>
				<input type="password" name="password" id="login_password" value="" class="text requiredField"/>
			</fieldset>
			<br>
			<fieldset>
				<input name="user_login_submit" value="Login" class="button small red" type="submit"/>
			</fieldset>
			<a href="/user/forgot">Forgot your password?</a><br />
			<a href="#" id="user_register_show" class="login_register_show hide">Create new TPX account</a>
		</form>
	</div>
	
	<div id="user_register" class="login_register">
	<h4>Register a new TPX account</h4>
	<form action="/auth/register" id="register_form" method="post">
		<input type="hidden" name="redir" value="/">
		<fieldset>
			<label>Are you looking to be a TPX girl or a standard user? <span class="required">*</span></label>
			<input type="radio" name="role_id" value="2" class="radio requiredField" checked /> &nbsp; Standard user<br />
			<input type="radio" name="role_id" value="3" class="radio requiredField" /> &nbsp; TPX girl
		</fieldset>
		<fieldset>
			<label>Email <span class="required">*</span></label>
			<input type="text" name="email" id="register_email" value="" class="text requiredField email" />
		</fieldset>
		<fieldset>
			<label>Screen name <span class="required">*</span></label>
			<input type="text" name="screenname" id="register_username" value="" class="text requiredField email" />
		</fieldset>
		<fieldset>
			<label>Password <span class="required">*</span></label>
			<input type="password" name="password" id="password" value="" class="text requiredField subject" />
		</fieldset>
		<fieldset>
			<label>Password (Again) <span class="required">*</span></label>
			<input type="password" name="password2" id="password2" value="" class="text requiredField subject" />
		</fieldset>
		<br>
		<fieldset>
			<input name="user_register_submit" value="Create account" class="button small red" type="submit" />
		</fieldset>
		<a href="#" id="user_login_show" class="login_register_show hide">I have a password. Sign in.</a>
	</form>
	</div>

</div>
