<script type="text/javascript">
    var imgPath = '<?php echo $this->baseUrl('images/');?>';
    jQuery(document).ready(function() {
        openid.img_path = imgPath;
        openid.init('openid_identifier');
        openid.setDemoMode(false); //Stops form submission for client javascript-only test purposes
    });
</script>
<?php Jien::debug($this->User);?>

<div style="clear:both;padding:30px 29px;width:360px;background-color:black;">

	<img src="<?php echo $this->profile_image_url; ?>" style="width:200px;height:300px;" />
	
	<?php echo $this->user['first_name'] . ' ' . substr($this->user['last_name'], 0,1);?>
	

</div>


<div class="horizontal-line"></div>