<script type="text/javascript">
    var imgPath = '<?php echo $this->baseUrl('images/');?>';
    jQuery(document).ready(function() {
        openid.img_path = imgPath;
        openid.init('openid_identifier');
        openid.setDemoMode(false); //Stops form submission for client javascript-only test purposes
    });
</script>


<div style="width:418px;float:left;">
	<div id="profile">
		<div class="utility edit">Edit Profile</div>
		<img src="<?php echo $this->profile_image_url; ?>" style="width:200px;height:300px;margin: 0 23px 26px 0;float:left;" />
		<h1><?php echo $this->User['screenname'];?></h1>
		<h2>
			<span>25</span>
			<input name="age" type="text" value="" />
		</h2>
		<p class="blurb">
			<span>I'm just a girl who has fun everyday and everywhere.</span>
			<textarea name="quote"></textarea>
		</p>
		<div>
		<div class="twitter-link">
			@<span>katess1244</span>
			<input type="text" name="twitter_name" val="" style="width:50px;"/>
		</div>
		<div class="facebook-verified">verified &#x2713;</div>
		</div>
		<div style="clear:both"></div>
		<ul>
			<li>
				<strong>Hometown</strong>
				<span>Chicago, IL</span>
				<input name="hometown" type="text" value="" />
			</li>
			<li>
				<strong>Relgion</strong>
				<span>Great Mystery</span>
				<input name="religion" type="text" value="" />
			</li>
			<li>
				<strong>Relationship Status</strong>
				<span>Single</span>
				<input name="relationship_status" type="text" value="" />
			</li>
			<li>
				<strong>Social</strong>
				<span>Outgoing</span>
				<input name="social" type="text" value="" />
			</li>
			<li>
				<strong>Hair Color</strong>
				<span>Brunette</span>
				<input name="hair_color" type="text" value="" />
			</li>
			<li>
				<strong>Meat Lover</strong>
				<span>Love it</span>
				<input name="meat_lover" type="text" value="" />
			</li>
			<li>
				<strong>Education</strong>
				<span>College</span>
				<input name="education" type="text" value="" />
			</li>
			<li>
				<strong>Panty of Choice</strong>
				<span>Thong</span>
				<input name="panty_style" type="text" value="" />
			</li>
			<li>
				<strong>Outlook</strong>
				<span>Optimist</span>
				<input name="outlook" type="text" value="" />
			</li>
		</ul>
		<div style="clear:both"></div>
	</div>
</div>

<script type="text/javascript">
$(document).ready(function() { 
	
	var save = true;
	$(".utility").click (function() {
		if (save == true) {
			$(this).text('Save Changes');
			$("#profile ul li input, #profile h2 input, .twitter-link input, .blurb textarea").show();
			$("#profile ul li span, #profile h2 span, .twitter-link span, .blurb span").hide();
			$.each($("#profile ul li"), function(k,v) {
				var property = $(this).children("span").text();
				$(this).children("input").val(property);
			});
			$('#profile h2 input').val($('#profile h2 span').text());
			$('.twitter-link input').val($('.twitter-link span').text());
			$('.blurb textarea').val($('.blurb span').text());
			save = false;
		} else {
			var age = $('input[name="age"]').val();
			var quote = $('textarea[name="blurb"]').val();
			var twitter_name = $('input[name="twitter_name"]').val();
			var city = $('input[name="hometown"]').val();
			var religion = $('input[name="religion"]').val();
			var social = $('input[name="social"]').val();
			var relationship_status = $('input[name="relationship_status"]').val();
			var hair_color = $('input[name="hair_color"]').val();
			var meat_lover = $('input[name="meat_lover"]').val();
			var education = $('input[name="education"]').val();
			var panty_choice = $('input[name="panty_choice"]').val();
			var outlook = $('input[name="outlook"]').val();
			var data = {'user_profile_update':'Save Profile',
						'birthday':age, 'quote':quote, 'twitter_name':twitter_name, 'city':city,
						'religion':religion, 'social':social, 'relationship_status':relationship_status,
						'hair_color':hair_color,'meat_lover':meat_lover,'education':education,
						'panty_choice':panty_choice,'outlook':outlook};
			$.post("/user/profile", data, function(res) {
				if(res[0] != 0) {
					
				}
				console.log(res);
			});
			$(this).text('Edit Profile');
			$.each($("#profile ul li"), function(k,v) {
				var property = $(this).children("input").val();
				$(this).children("span").text(property);
			});
			$('#profile h2 span').text($('#profile h2 input').val());
			$('.twitter-link span').text($('.twitter-link input').val());
			$('.blurb span').text($('.blurb textarea').val());
			$("#profile ul li input, #profile h2 input, .twitter-link input, .blurb textarea").hide();
			$("#profile ul li span,  #profile h2 span, .twitter-link span, .blurb span").show();
			save = true;
		}
	});
});
</script>
