<script type="text/javascript">
    var imgPath = '<?php echo $this->baseUrl('images/');?>';
    jQuery(document).ready(function() {
        openid.img_path = imgPath;
        openid.init('openid_identifier');
        openid.setDemoMode(false); //Stops form submission for client javascript-only test purposes
    });
</script>


<div style="width:418px;float:left;">
	<div id="profile">
		<div class="utility edit">Edit Profile</div>
		<img src="<?php echo $this->profile_image_url; ?>" style="width:200px;height:300px;margin: 0 23px 26px 0;float:left;" />
		
		<h1>Kate S.</h1>
		<h2>25, Chicago</h2>
		<p class="blurb">I'm just a girl who has fun everyday and everywhere.</p>
		<div>
		<a href="" target="_blank" class="twitter-link">@katess1244</a>
		<div class="facebook-verified">verified &#x2713;</div>
		</div>
		<div style="clear:both"></div>
		<ul>
			<input type="hidden" name="user_profile_update" value="Save Profile" />
			<li>
				<strong>Hometown</strong>
				<span>Chicago, IL</span>
				<input name="hometown" type="text" value="" />
			</li>
			<li>
				<strong>Relgion</strong>
				<span>Great Mystery</span>
				<input name="religion" type="text" value="" />
			</li>
			<li>
				<strong>Relationship Status</strong>
				<span>Single</span>
				<input name="relationship_status" type="text" value="" />
			</li>
			<li>
				<strong>Social</strong>
				<span>Outgoing</span>
				<input name="social" type="text" value="" />
			</li>
			<li>
				<strong>Hair Color</strong>
				<span>Brunette</span>
				<input name="hair_color" type="text" value="" />
			</li>
			<li>
				<strong>Meat Lover</strong>
				<span>Love it</span>
				<input name="meat_lover" type="text" value="" />
			</li>
			<li>
				<strong>Education</strong>
				<span>College</span>
				<input name="education" type="text" value="" />
			</li>
			<li>
				<strong>Panty of Choice</strong>
				<span>Thong</span>
				<input name="panty_style" type="text" value="" />
			</li>
			<li>
				<strong>Outlook</strong>
				<span>Optimist</span>
				<input name="outlook" type="text" value="" />
			</li>
		</ul>
		<div style="clear:both"></div>
	</div>
</div>

<script type="text/javascript">
$(document).ready(function() { 
	
	var save = true;
	$(".utility").click (function() {
		if (save == true) {
			$(this).text('Save Changes');
			$("#profile ul li input").show();
			$("#profile ul li span").hide();
			$.each($("#profile ul li"), function(k,v) {
				var property = $(this).children("span").text();
			});
			save = false;
		} else {
			$(this).text('Edit Profile');
			$("#profile ul li input").hide();
			$("#profile ul li span").show();
			save = true;
			var data = {'name':name, 'where':where, 'when':when, 'notes':notes};
			$.post("/user/profile", data, function(res) {
				if(res[0] != 0) {
				}
			});
		}
	});
});
</script>
