<?php
$latestPosts = Jien::model("Post")->byLatest()->limit(5)->getAll();
?>

<span class="colored">CLEAN &amp; SIMPLE TEMPLATE</span>
<p>
	 Arripuit plorabis filiam vel regio hinc indica enim materiam. Crede respiciens forsitan Apollonius ut libertatem accipies. Addicitur quid populi civitatis ne videret famis perisse naufrago in lucem in modo genito in lucem exitum atque album Apolloni sed.
</p>
<p>
	 Viam iube meae ceroma fronte comico hac auxilium volo, interea applicuit defunctam lacrimis V signa ad nomine. Dionysiadem in modo ad te ad per sanctus singulo.
</p>

<div class="horizontal-line">
</div>
<h4 class="blog-category">Our Categories</h4>
<ul class="simple-nav">
	<!--SIMPLE UL -->
	<li><a href="about-us.html">Design</a> (21)</li>
	<li><a href="our-team.html">Programming</a> (28)</li>
	<li><a href="career.html">Video Manipulation</a> (9)</li>
	<li><a href="services-item.html">Freebies</a> (32)</li>
	<li><a href="testimonials.html">Typography</a> (14)</li>
	<li><a href="blog.html">Inspiration</a> (34)</li>
	<li><a href="portfolio-four-columns.html">Other Topics</a> (38)</li>
</ul>
<div class="horizontal-line">
</div>
<h4 class="blog-category">Latest Posts</h4>

<ul>
	<!-- LATEST POSTS UL-->
	<?php foreach($latestPosts->dataset AS $record){ ?>
	<li>
	<a href="/blog/post/id/<?php echo $record['post_id']; ?>"><?php echo $record['subject']; ?></a>
	<p>
		<span><?php echo date("F, d, Y", strtotime($record['created'])); ?> <a href="/blog/post/id/<?php echo $record['post_id']; ?>#disqus_thread">Loading ...</a></span>
	</p>
	</li>
	<?php } ?>

</ul>