
			<div id="content">
				<div class="one">
					<!-- COLUMNS CONTAINER STARTS-->
					<div class="intro-pages">
						<!-- INTRO DIV STARTS-->
						<h3>Welcome to <span class="colored">Adventure</span>, Clean &amp; Simple <span class="colored">HTML5 </span> template.Feel free to browse through all the pages and see what's &quot;Adventure&quot; capable to do for You.Enjoy! </h3>
					</div>
					<!-- INTRO ENDS-->
				</div>
				<!-- COLUMNS CONTAINER ENDS-->
				<div class="one">
					<div class="inner-content">

					<?php if($this->data->dataset){ ?>

							<?php foreach($this->data->dataset AS $key=>$record){ ?>
								<h3><a href="/blog/post/id/<?php echo $record['post_id']; ?>"><?php echo $record['subject']; ?></a></h3>
								<p>
									 Posted by: <a href="/user/profile/id/<?php echo $record['user_id']; ?>"><?php echo $record['username']; ?></a> on <?php echo date("F, d, Y", strtotime($record['created'])); ?> | <a href="/blog/post/id/<?php echo $record['post_id']; ?>#disqus_thread">Loading ...</a>
								</p>
								<!--POST DETAILS-->
								<!--POST INTRO-->
								<p>
									 <?php echo $record['message']; ?>
									 <div style="clear:both;"></div>
								</p>
								<a href="/blog/post/id/<?php echo $record['post_id']; ?>">Read This Article</a>

								<!--POST LINK-->
								<div class="horizontal-line">
								</div>

							<?php } ?>


						<!--PAGINATION-->
						<?php echo $this->paginator($this->data); ?>
						<!--<ul class="blog-pagination">
							<li><a href="#"><b>page 1 of 7</b></a></li>
							<li class="current"><a href="#">1</a></li>
							<li><a href="#">2</a></li>
							<li><a href="#">3</a></li>
							<li><a href="#">4</a></li>
							<li><a href="#">5</a></li>
							<li><a href="#">6</a></li>
							<li><a href="#">7</a></li>
							<li><a href="#">Next</a></li>
						</ul>-->
						<!--PAGINATION ENDS-->


					<?php }else{ ?>

						<h3>There are no records found</h3>
						<p>
							Please refine your search keyword and try again ...
						</p>

					<?php } ?>



					</div>
					<div class="one-fourth last">
						<?php echo $this->partial('partials/side.phtml'); ?>
					</div>
					<!-- COLUMNS CONTAINER ENDS-->
				</div>

<script type="text/javascript">
/* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
var disqus_shortname = '<?php echo DISQUS_ID; ?>'; // required: replace example with your forum shortname
<?php if(APPLICATION_ENV != 'prod'){ ?>
var disqus_developer = 1;
<?php } ?>

/* * * DON'T EDIT BELOW THIS LINE * * */
(function () {
    var s = document.createElement('script'); s.async = true;
    s.type = 'text/javascript';
    s.src = 'http://' + disqus_shortname + '.disqus.com/count.js';
    (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script>