<!-- MAIN CONTAINER -->
<div id="content">

	<div class="one">
		<div class="one-fourth">
			<?php echo $this->partial('partials/pages.phtml'); ?>
		</div>
		<div class="inner-content last">
			<?php

			// page found from db
			if(!empty($this->content)){
				echo $this->content;

			// load from static file
			}else{
				echo $this->partial($this->file);
			}
			?>
		</div>

	</div>
	<!-- CONTENT ENDS-->
</div>