<?php
$categories = Jien::model("Category")->orderBy("category.category_id ASC")->getAll();
$category_dropdown = "<select name='parent_id'>";
$category_dropdown .= "<option value='0'></option>";
foreach($categories['records'] AS $category){
	$sel = '';
	$category_dropdown .= "<option {$sel} value='{$category['category_id']}'>{$category['category']}</option>";
}
$category_dropdown .= "</select>";
?>

<div class="left" style="width:20%;">

	<div class="content">

		<div>
			<h4><a href="/admin/<?php echo strtolower($this->model); ?>s"><-- Back to <?php echo $this->model; ?>s</a></h4>
		</div>

		<div class="row">
		  <div class="span10">
		  	<ul class="content_menu menu">
		  		<!-- <li><a href="#basic_info">Basic <?php echo strtolower($this->model); ?> info</a></li> -->
		  	</ul>

		  </div>
		</div>

	</div>

</div>

<div class="left">

	<div class="content">

		<div class="page-header">
		  <h3>
		  	<?php if($this->params('id')){ ?>
		  		Update <?php echo strtolower($this->model); ?>
		  	<?php }else { ?>
		  		Add <?php echo strtolower($this->model); ?>
		  	<?php } ?>
		  </h3>
		</div>

		<div class="row">
		  	<div class="span12">
		  		<form class="trig_save" action="/admin/data" method="POST">
		  			<input type="hidden" name="model" value="<?php echo $this->model; ?>">
		  			<input type="hidden" name="id" value="<?php echo $this->params('id'); ?>">

			        <fieldset>

						<legend><a name="basic_info"></a> Basic info</legend>

						<div class="clearfix">
							<label for="xlInput">Type</label>
							<div class="input">
								<input class='large' name='type' value="<?php echo !empty($this->data['type']) ? $this->data['type'] : 'Post'; ?>" type='text'>
							</div>
						</div>

						<div class="clearfix">
							<label for="xlInput">Parent</label>
							<div class="input">
								<?php echo $category_dropdown; ?>
							</div>
						</div>

						<div class="clearfix">
							<label for="xlInput">Category</label>
							<div class="input">
								<input class='large' name='category' value="<?php echo !empty($this->data['category']) ? $this->data['category'] : ''; ?>" type='text'>
							</div>
						</div>


			        </fieldset>

			        <fieldset>
			          <div class="actions">
			            <input type="submit" class="btn primary" value="Save changes">&nbsp;<button type="reset" class="btn back">Cancel</button>
			          </div>
			        </fieldset>
			      </form>
		  	</div>
		</div>

	</div>

</div>
