<?php

?>

<div class="left">

	<div class="content">

		<div class="page-header">
			<h3>
		  		Listing all <?php echo $this->model; ?>s <small></small> <span class='right'><a href='/admin/<?php echo strtolower($this->model); ?>?type=<?php echo $this->params('type'); ?>'>Add a <?php echo strtolower($this->model); ?></a></span>
		  	</h3>
		</div>

		<div class="row">
		  	<div class="span12">
		    	<?php echo $this->paginator($this->data, true); ?>
		  	</div>
		</div>

		<div class="row">
		  	<div class="span15">
				<div>
					<p>
						By Type:
						<select class="filter dropdown" rel="type">
							<?php echo $this->dropdownOptions(array(
								"",
								"Post"	=>	"Post",
							), $this->params('type', 'Post'));
							?>
						</select>
					</p>
				</div>
		  		<table>
			        <thead>
			          <tr>
			            <th class="header">#</th>
			            <th class="header">Type</th>
			            <th class="header">Category</th>
			            <th class="header">Path</th>
			            <th class="header">Created</th>
			            <th class="header">Action</th>
			          </tr>
			        </thead>
			        <tbody>
			        <?php foreach($this->data->dataset AS $key=>$value){ ?>
			        <tr>
			            <td><?php echo $value['category_id']; ?></td>
			            <td><?php echo $value['type']; ?></td>
			            <td><?php echo $value['category']; ?></td>
			            <td><?php echo $value['path']; ?></td>
			            <td><?php echo date("m/d/y", strtotime($value['created'])); ?></td>
			            <td>
			            	<a href="/admin/<?php echo strtolower($this->model); ?>/id/<?php echo $value[strtolower($this->model).'_id']; ?>" class="btn blue">Edit</a>
			            	<a href="/admin/delete/?model=<?php echo $this->model; ?>&id=<?php echo $value[strtolower($this->model).'_id'];; ?>" class="btn red trig_delete" rel="model=<?php echo $this->model; ?>|id=<?php echo $value[$this->primary]; ?>">Remove</a>
			            </td>
			          </tr>
			          <?php } ?>
			          </tbody>
			      </table>

			     <?php echo $this->paginator($this->data); ?>
		  	</div>



		</div>

	</div>

</div>

