
<div class="left" style="width:20%;">

	<div class="content">

		<div>
			<h4><a href="/admin/categories"><-- Back to categories</a></h4>
		</div>

		<div class="row">
		  <div class="span10">
		  	<ul class="content_menu menu">
		  		<!-- <li><a href="#basic_info">Basic <?php echo strtolower($this->model); ?> info</a></li> -->
		  	</ul>

		  </div>
		</div>

	</div>

</div>

<div class="left">

	<div class="content">

		<div class="page-header">
		  <h3>
		  	<?php if($this->params('id')){ ?>
		  		Update <?php echo strtolower($this->model); ?>
		  	<?php }else { ?>
		  		Add <?php echo strtolower($this->model); ?>
		  	<?php } ?>
		  </h3>
		</div>

		<div class="row">
		  	<div class="span12">
		  		<form class="trig_save" action="/admin/data" method="POST">
		  			<input type="hidden" name="model" value="<?php echo $this->model; ?>">
		  			<input type="hidden" name="id" value="<?php echo $this->params('id'); ?>">

			        <fieldset>

						<legend><a name="basic_info"></a> Basic info</legend>

						<div class="clearfix">
							<label for="xlInput">Type</label>
							<div class="input">
								<input class='large disabled' name='type' value="<?php echo $this->params('type') != '' ? $this->params('type') : (!empty($this->data->dataset['type']) ? $this->data->dataset['type'] : 'Post'); ?>" type='text'>
							</div>
						</div>

						<div class="clearfix">
							<label for="xlInput">Parent</label>
							<div class="input">
								<select name='parent_id'>
									<?php echo $this->CategoryDropdown($this->params('type', $this->data->dataset['type']), !empty($this->data->dataset['parent_id']) ? $this->data->dataset['parent_id'] : $this->params('category_id')); ?>
								</select>
							</div>
						</div>

						<div class="clearfix">
							<label for="xlInput">Category</label>
							<div class="input">
								<input class='large' name='category' value="<?php echo !empty($this->data->dataset['category']) ? $this->data->dataset['category'] : ''; ?>" type='text'>
							</div>
						</div>


			        </fieldset>

			        <fieldset>
			          <div class="actions">
			            <input type="submit" class="btn primary" value="Save changes">&nbsp;<button type="reset" class="btn back">Cancel</button>
			          </div>
			        </fieldset>
			      </form>
		  	</div>
		</div>

	</div>

</div>
