
<header class="jumbotron subhead" id="overview">
  <div class="inner">
    <div class="container">
      <h1>Administrator Page</h1>
      <p class="lead">
        Gain access to top secret stats and more ...
      </p>
    </div><!-- /container -->
  </div>
</header>

<div class="container" style='padding-top: 20px;'>

	<div class="content">
		<div class="page-header">
		  <h1>Wait ...<small> You are not logged in </small></h1>
		</div>
		<div class="row">
		  <div class="span10">
		    <p>If you are having difficulty, please contact the site administrator.</p>
		    <p>Click here if you <a href="/admin/forgot-pass">forgot your password</a>.</p>
		  </div>
		</div>
	</div>
	
</div>