<div class="left" style="width:20%;">

	<div class="content">

		<div>
			<h4><a href="/admin/<?php echo strtolower($this->model); ?>s"><-- Back to <?php echo $this->model; ?>s</a></h4>
		</div>

		<div class="row">
		  <div class="span10">
		  	<ul class="content_menu menu">
		  		<!-- <li><a href="#basic_info">Basic <?php echo strtolower($this->model); ?> info</a></li> -->
		  	</ul>

		  </div>
		</div>

	</div>

</div>

<div class="left">

	<div class="content">

		<div class="page-header">
		  <h3>
		  	<?php if($this->params('id')){ ?>
		  		Update <?php echo strtolower($this->model); ?>
		  	<?php }else { ?>
		  		Add <?php echo strtolower($this->model); ?>
		  	<?php } ?>
		  </h3>
		</div>

		<div class="row">
		  	<div class="span12">
		  		<form class="trig_save" action="/admin/data" method="POST">
		  			<input type="hidden" name="model" value="<?php echo $this->model; ?>">
		  			<input type="hidden" name="id" value="<?php echo $this->params('id'); ?>">
		  			<input type="hidden" name="user_id" value="<?php echo $this->data->row('user_id') ? $this->data->row('user_id') : $_SESSION['user']->user_id; ?>">
			        <fieldset>

						<legend><a name="basic_info"></a> Basic info</legend>

						<?php if($this->data->row('username')){ ?>
						<div class="clearfix">
							<label for="xlInput">Username</label>
							<div class="input">
								<input type="text" class="medium disabled" disabled value="<?php echo $this->data->row('username'); ?>">
							</div>
						</div>
						<?php } ?>

						<div class="clearfix">
							<label for="xlInput">Category</label>
							<div class="input">
								<select name='category_id'>
									<?php echo $this->CategoryDropdown('Post', $this->params('category_id', $this->data->row('category_id'))); ?>
								</select>

							</div>
						</div>

						<div class="clearfix">
							<label for="xlInput">Subject</label>
							<div class="input">
								<input class='xxlarge' name='subject' value="<?php echo $this->data->row('subject') ? $this->data->row('subject') : ''; ?>" type='text'>
							</div>
						</div>

						<div class="clearfix">
							<label for="xlInput">Message</label>
							<div class="input">
								<textarea name="message" rows='5' class='xxlarge wysiwyg'><?php echo $this->data->row('message') ? $this->data->row('message') : ''; ?></textarea>
							</div>
						</div>

						<div class="clearfix">
							<label for="xlInput">Status</label>
							<div class="input">
								<select name="status">
									<?php echo $this->dropdownOptions(array(
										"pending"	=>	"Pending",
										"published"	=>	"Published",
									), $this->data->row('status'), 'published'); ?>
								</select>
							</div>
						</div>

			        </fieldset>

			        <fieldset>
			          <div class="actions">
			            <input type="submit" class="btn primary" value="Save changes">&nbsp;<button type="reset" class="btn back">Cancel</button>
			          </div>
			        </fieldset>
			      </form>
		  	</div>
		</div>

	</div>

</div>
