
<div class="left">

	<div class="content">

		<div class="page-header">
			<h3>
		  		Listing all <?php echo $this->model; ?>s <small></small> <span class='right'><a href='/admin/<?php echo strtolower($this->model); ?>'>Add a <?php echo strtolower($this->model); ?></a></span>
		  	</h3>
		</div>

		<div class="row">
		  	<div class="span12">
		    	<?php echo $this->pager($this->data->pager(), 'partials/pager/text_only.phtml'); ?>
		  	</div>
		</div>

		<div class="row">
		  	<div class="span15">

		  		<table class="zebra-striped">
			        <thead>
			          <tr>
			            <th class="header" rel="u.user_id">#</th>
			            <th class="header" rel="u.username">Username</th>
			            <th class="header" rel="u.email">Email</th>
			            <th class="header" rel="u.role_id">Role</th>
			            <th class="header" rel="u.created">Joined</th>
			            <th class="header">Action</th>
			          </tr>
			        </thead>
			        <tbody>
			        <?php foreach($this->data->rows() AS $key=>$value){ ?>
			        <tr>
			            <td><?php echo $value['user_id']; ?></td>
			            <td>
			            	<?php
			            		switch($value['provider']){
			            			case "facebook":
			            				echo "<a href='http://facebook.com/{$value['username']}' target='_blank'><img src='/images/icons/facebook.png' width='15'></a>";
			            			break;

			            			case "twitter":
			            				echo "<a href='http://twitter.com/{$value['username']}' target='_blank'><img src='/images/icons/twitter.png' width='15'></a>";
			            			break;
			            		}
			            	?>
			            	<?php echo $value['username']; ?>
			            </td>
			            <td><?php echo $value['email']; ?></td>
			            <td><?php echo $value['role']; ?></td>
			            <td><?php echo date("m/d/y", strtotime($value['created'])); ?></td>
			            <td>
			            	<a href="/admin/<?php echo strtolower($this->model); ?>/id/<?php echo $value[$this->primary]; ?>" class="btn blue">Edit</a>
			            	<a href="/admin/delete/?model=<?php echo $this->model; ?>&id=<?php echo $value[$this->primary];; ?>" class="btn red trig_delete" rel="model=<?php echo $this->model; ?>|id=<?php echo $value[$this->primary]; ?>">Remove</a>
			            </td>
			          </tr>
			          <?php } ?>
			          </tbody>
			      </table>

			     <?php echo $this->pager($this->data->pager(), 'partials/pager/pager.phtml'); ?>
		  	</div>



		</div>

	</div>

</div>

