<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>Jien</title>
	
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js" type="text/javascript"></script>
	<script src="/js/jien.js" type="text/javascript"></script>
	<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" type="text/javascript"></script>
	<script src="http://twitter.github.com/bootstrap/1.3.0/bootstrap-dropdown.js" type="text/javascript"></script>
	<script src="http://twitter.github.com/bootstrap/1.3.0/bootstrap-twipsy.js" type="text/javascript"></script>
	<script src="http://twitter.github.com/bootstrap/1.3.0/bootstrap-scrollspy.js" type="text/javascript"></script>
	<script src="http://twitter.github.com/bootstrap/1.3.0/bootstrap-alerts.js" type="text/javascript"></script>
	<script src="http://twitter.github.com/bootstrap/1.3.0/bootstrap-popover.js" type="text/javascript"></script>
	<script src="http://twitter.github.com/bootstrap/1.3.0/bootstrap-tabs.js" type="text/javascript"></script>
	<script src="http://twitter.github.com/bootstrap/1.3.0/bootstrap-modal.js" type="text/javascript"></script>
	
	<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/base/jquery-ui.css" type="text/css" media="all" />
	<link rel="stylesheet" href="http://static.jquery.com/ui/css/demo-docs-theme/ui.theme.css" type="text/css" media="all" />
	<link rel="stylesheet" href="http://twitter.github.com/bootstrap/1.3.0/bootstrap.min.css">
	<link rel="stylesheet" href="http://twitter.github.com/bootstrap/assets/css/docs.css">
	<link rel="stylesheet" href="/css/admin.css">
	<link rel="stylesheet" href="/css/pagination.css">
	
	<script src="/js/plugins/toastmessage/jquery.toastmessage.js" type="text/javascript"></script>
	<link rel="stylesheet" href="/js/plugins/toastmessage/css/jquery.toastmessage.css">

</head>

 <body>
 
    <div class="topbar">
      <div class="fill">
        <div class="container">
          <a class="brand" href="/admin">Admin</a>
          <ul class="nav" id="main_menu">
            <li class="active"><a href="/admin">Home</a></li>
            <li><a href="/admin/users">Users</a></li>
            <li><a href="/admin/posts">Posts</a></li>
            <li><a href="/admin/pages">Pages</a></li>
          </ul>
          
          <?php if(!empty($_SESSION['user'])){ ?>
          <ul id="profile" class="nav secondary-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle">jaequery</a>
              <ul class="dropdown-menu">
              	<li><a href="/admin/user/id/<?php echo $_SESSION['user']->user_id; ?>">Settings</a></li>
                <li><a href="/auth/logout" class='trig_logout'>Log-out</a></li>
              </ul>
            </li>
          </ul>
          <?php } ?>

          <?php if(empty($_SESSION['user'])){ ?>
          <form action="/auth/login" method="POST" id="login_form" class="pull-right">
            <input class="input-small" type="text" placeholder="username" name="username">
            <input class="input-small" type="password" placeholder="password" name="password">
            <button class="btn" type="submit">Sign in</button>
          </form>
          <script>
          $(document).ready(function(){
          	$('#login_form input[name=username]').focus();
          });
          </script>
          <?php } ?>
        </div>
      </div>
    </div>

    <div id="main" class="main">
    	<div class="container">
			<?php echo $this->layout()->content; ?>	
		</div>
	</div>
	
	<div class="container" style="padding-left: 40px;">
	    	<p> Powered by Jien Framework &copy; All rights reserved.</p>
	</div>
    
	
	
	<!--domready javascript-->
  	<script>
  	
  	/** onready events **/
  	
  	// enable dropdown
  	$('#profile').dropdown();

  	// enable active menu highlighting
  	$('#main_menu li').removeClass('active');
  	
  	// login event
  	$('#login_form').submit(function(e){
		e.preventDefault();
		var form = site.util.serializeForm($(this));
		$.post("/auth/login", form, function(res){
			if(res.result.code == 200){
				window.location.href = '/admin/dashboard';	
			}else{
				alert('invalid user/pass');
				$('#login_form input[name=username]').focus();
			}
			
		});
  	});
  	
  	// logout event
  	$('.trig_logout').click(function(e){
  		e.preventDefault();
  		$.post("/auth/logout", function(res){
  			window.location.href = '/admin';
  		});
  	});
  	
  	// save form event
  	$('form.trig_save').submit(function(e){
		e.preventDefault();
		var data = jien.util.serializeForm(this);
		$.post("/admin/data", data, function(res){
			if(res.status.code == 200){
				jien.ui.growl('Saved!');
				history.go(-1);
			}else{
				jien.ui.growl(res.status.text, 'error');
			}
		});
  	});
  	
  	// delete event
  	$('a.trig_delete').click(function(e){
  		e.preventDefault();
  		var c = confirm('Are you sure?');
  		if(c){
	  		var opts = jien.util.parseRel($(this).attr('rel'));
	  		opts.cmd = 'delete';
	  		var self = this;
	  		$.post("/admin/data", opts, function(res){
	  			if(res.status.code == 200){
	  				jien.ui.growl('Deleted');
	  				$(self).parent().parent().slideUp();
	  			}else{
	  				jien.ui.growl(res.status.text, 'error');
	  			}
	  		});
  		}
  	});
  	
  	</script>
  	
  	
  	
    
  </body>
  
	
</html>