<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?php echo $this->title; ?></title>

<link href="/css/main.css" rel="stylesheet" type="text/css" />
<link href="/css/home.css" rel="stylesheet" type="text/css" />

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript" src="/js/cufon-yui.js"></script>
<script type="text/javascript" src="/js/HelveticaSTDBlackCondensed.js"></script>
<script type="text/javascript" src="/js/HelveticaSTDLightCondensed.js"></script>
<script type="text/javascript" src="/js/main.js"></script>
<script type="text/javascript" src="/js/slider.js"></script>
<script>
var twitter_id = "<?php echo TWITTER_ID; ?>";
var disqus_shortname = '<?php echo DISQUS_ID; ?>';
</script>

</head>

<body>

<script>
$ = jQuery;
$(document).ready(function(){

<?php
$flash = $this->flashMessenger();
if($flash){
?>
	$.gritter.add({
		// (string | mandatory) the heading of the notification
		title: ' ',
		// (string | mandatory) the text inside the notification
		text: "<?php echo strip_tags(addslashes($flash)); ?>"
	});
	return false;
<?php } ?>
});
</script>


<div id="wrapper">

	<div id="header">
    	<a href="/" id="logo"></a>
        <div id="login"><a href="">LOGIN</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="">HELP</a></div>
        <div id="menu">
        	<a href="">ABOUT</a>&nbsp;&nbsp;/&nbsp;
            <a href="battle.html">BATTLE</a>&nbsp;&nbsp;/&nbsp;
            <a href="">LEARN</a>&nbsp;&nbsp;/&nbsp;
            <a href="">OUR LADIES</a>
        </div>
    </div>
    
	<?php
		echo $this->layout()->content;
	?>
	
	
    <div style="clear: both"></div>
    
    <div id="footer">
        <div id="footer-logo"></div>
    </div>
    
</div><!-- #wrapper -->

<script>
// login event
$(document).ready(function(){
	$('#login_form').submit(function(e){
		e.preventDefault();
		var form = jien.util.serializeForm($(this));
		$.post("/auth/login", form, function(res){
			if(res.status.code == 200){
				$().toastmessage('showSuccessToast', 'Success');
				window.location.href = form.redir;
			}else{
				$().toastmessage('showErrorToast', res.result.msg);
				$('#login_form input[name='+res.result.focus+']').focus();
			}
		});
	});

	$('#register_form').submit(function(e){
		e.preventDefault();
		var form = jien.util.serializeForm($(this));
		$.post("/auth/register", form, function(res){
			if(res.status.code == 200){
				$().toastmessage('showSuccessToast', 'Success');
				window.location.href = form.redir;
			}else{
				$().toastmessage('showErrorToast', res.result.msg);
				$('#register_form input[name='+res.result.focus+']').focus();
			}
		});
	});

	$('#user_login_show').click(function(e){
		$('.login_register_show').hide();
		$('.login_register').hide();
		$('#user_register_show').show();
		$('#user_login').show();
	});

	$('#user_register_show').click(function(e){
		$('.login_register_show').hide();
		$('.login_register').hide();
		$('#user_login_show').show();
		$('#user_register').show();
	});

});
</script>

</body>
</html>
