
			<div id="content">
				<div class="one">
					<!-- COLUMNS CONTAINER STARTS-->
					<div class="intro-pages">
						<!-- INTRO DIV STARTS-->
						<h3>Welcome to <span class="colored">Adventure</span>, Clean &amp; Simple <span class="colored">HTML5 </span> template.Feel free to browse through all the pages and see what's &quot;Adventure&quot; capable to do for You.Enjoy! </h3>
					</div>
					<!-- INTRO ENDS-->
				</div>
				<!-- COLUMNS CONTAINER ENDS-->
				<div class="one">
					<div class="inner-content">

					<?php if($this->data->rows()){ ?>

							<?php foreach($this->data->rows() AS $key=>$row){ ?>
								<h3><a href="/blog/post/id/<?php echo $row['post_id']; ?>"><?php echo $row['subject']; ?></a></h3>
								<p>
									 Posted by: <a href="/user/profile/id/<?php echo $row['user_id']; ?>"><?php echo $row['username']; ?></a> on <?php echo date("F, d, Y", strtotime($row['created'])); ?> | <a href="/blog/post/id/<?php echo $row['post_id']; ?>#disqus_thread">Loading ...</a>
								</p>

								<!--POST DETAILS-->
								<!--POST INTRO-->
								<p>
									 <?php
									 	// echo substr(strip_tags($row['message']), 0, 400);
									 ?>
									 <?php echo $row['message']; ?>
									 <div style="clear:both;"></div>
								</p>
								<a href="/blog/post/id/<?php echo $row['post_id']; ?>">Read This Article</a>



								<!--POST LINK-->
								<div class="horizontal-line">
								</div>

							<?php } ?>


						<!--PAGINATION-->
						<?php echo $this->pager($this->data->pager(), 'partials/pager/pager.phtml'); ?>
						<!--PAGINATION ENDS-->


					<?php }else{ ?>

						<h3>There are no records found</h3>
						<p>
							Please refine your search keyword and try again ...
						</p>

					<?php } ?>



					</div>
					<div class="one-fourth last">
						<?php echo $this->partial('partials/side.phtml'); ?>
					</div>
					<!-- COLUMNS CONTAINER ENDS-->
				</div>

