			<div id="content">
				<div class="one">
			<div class="slideshow">
				<div id="slides">
				<div id="slider-big">
							<div class="slides_container big-slider">
								<!-- SLIDER STARTS-->
								<!-- SLIDER CONTENT STARTS-->
								<div class="slide">
									<img src="/themes/adventure/images/slideshow/slide-04.jpg" alt=" " width="950" height="350"/>
									<div class="caption">
										<p>Your Caption Goes Here!</p>
									</div>
								</div>
								<img src="/themes/adventure/images/slideshow/slide-02.jpg" alt=" " width="950" height="350"/>
								<div class="slide">
									<img src="/themes/adventure/images/slideshow/slide-03.jpg" alt=" " width="950" height="350"/>
									<div class="caption">
										<p>Your Caption Goes Here!</p>
									</div>
								</div>
								<img src="/themes/adventure/images/slideshow/slide-01.jpg" alt=" " width="950" height="350"/>
							</div>
							<!-- SLIDESHOW CONTAINER ENDS-->
						</div>
						<div class="slides-nav">

                    <a href="#" class="prev">Previous Slide</a>
                    <a href="#" class="next">Next Slide</a>

                <!--END .slides-nav -->
            	</div>
				</div>
				</div><!-- SLIDER ENDS-->	<!-- SLIDESHOW ENDS-->
			</div>
				<div class="one">
					<!-- COLUMNS CONTAINER STARTS-->
					<div class="intro-pages">
						<!-- INTRO DIV STARTS-->
						<h3>Welcome to <span class="colored">Adventure</span>, Clean &amp; Simple <span class="colored">HTML5 </span> template.Feel free to browse through all the pages and see what's &quot;Adventure&quot; capable to do for You.Enjoy! </h3>
					</div>
					<!-- INTRO ENDS-->
				</div>
				<!-- COLUMNS CONTAINER ENDS-->






				<div class="one">
					<div class="one-third">
						<img src="/themes/adventure/images/icons/idea.png" alt=" " class="img-align-left" width="66" height="66"/>
						<div class="text-align-left">
							<h4>Easy to Customize</h4>
							<p>
								Iuraveras magnifice ex auxilium super color est cum. Ripae simul navigat est amet constanter approximavit te.
							</p>
						</div>
					</div>
					<div class="one-third">
						<img src="/themes/adventure/images/icons/display.png" alt=" " class="img-align-left" width="66" height="66"/>
						<div class="text-align-left">
							<h4>Browsers Compatible</h4>
							<p>
								Iuraveras magnifice ex auxilium super color est cum. Ripae simul navigat est amet constanter approximavit te.
							</p>
						</div>
					</div>
					<div class="one-third last">
						<img src="/themes/adventure/images/icons/check-box.png" alt=" " class="img-align-left" width="66" height="66"/>
						<div class="text-align-left">
							<h4>Full Documentation</h4>
							<p>
								Iuraveras magnifice ex auxilium super color est cum. Ripae simul navigat est amet constanter approximavit te.
							</p>
						</div>
					</div>
					<div class="horizontal-line">
					</div>
				</div>
				<div class="one">
					<div class="one-fourth">
						<p>
							<a href="/themes/adventure/images/slideshow/slide-01.jpg" class="portfolio-item-preview" data-rel="prettyPhoto"><img src="/themes/adventure/images/portfolio/portfolio-img-04.jpg" alt=" " width="210" height="145" class="portfolio-img pretty-box"/></a>
						</p>
						<h4><a href="#">Awesome Design</a></h4>
						<p>
							 Lorem ipsum dolor sit amet, tollite fit manibus individuationis omnibus civitas ad quia.Amice suspiciosa mare non solutionem.
						</p>
						<a href="portfolio-four-columns.html">View entire Portfolio</a>
					</div>
					<div class="one-fourth">
						<p>
							<a href="/themes/adventure/images/slideshow/slide-01.jpg" class="portfolio-item-preview" data-rel="prettyPhoto"><img src="/themes/adventure/images/portfolio/portfolio-img-03.jpg" alt=" " width="210" height="145" class="portfolio-img pretty-box"/></a>
						</p>
						<h4><a href="#">Awesome Design</a></h4>
						<p>
							 Lorem ipsum dolor sit amet, tollite fit manibus individuationis omnibus civitas ad quia.Amice suspiciosa mare non solutionem.
						</p>
					</div>
					<div class="one-fourth">
						<p>
							<a href="/themes/adventure/images/slideshow/slide-01.jpg" class="portfolio-item-preview" data-rel="prettyPhoto"><img src="/themes/adventure/images/portfolio/portfolio-img-01.jpg" alt=" " width="210" height="145" class="portfolio-img pretty-box"/></a>
						</p>
						<h4><a href="#">Awesome Design</a></h4>
						<p>
							 Lorem ipsum dolor sit amet, tollite fit manibus individuationis omnibus civitas ad quia.Amice suspiciosa mare non solutionem.
						</p>
					</div>
					<div class="one-fourth last">
						<p>
							<a href="/themes/adventure/images/slideshow/slide-01.jpg" class="portfolio-item-preview" data-rel="prettyPhoto"><img src="/themes/adventure/images/portfolio/portfolio-img-02.jpg" alt=" " width="210" height="145" class="portfolio-img pretty-box"/></a>
						</p>
						<h4><a href="#">Wordpress logo</a></h4>
						<p>
							 Lorem ipsum dolor sit amet, tollite fit manibus individuationis omnibus civitas ad quia.Amice suspiciosa mare non solutionem.
						</p>
					</div>
				</div>
				<!-- COLUMNS CONTAINER ENDS-->
				<div class="one">
					<div class="horizontal-line">
					</div>
					<div class="one-fourth">
						<!-- COLUMN STARTS-->
						<h4><a href="#">Our Services &amp; More</a></h4>
						<p>
							 Lorem ipsum dolor sit amet, tollite fit manibus individuationis omnibus civitas ad quia. Quaere allocutus ait regem ut sua etiam quantitas non solutionem invenisti.
						</p>
					</div>
					<!-- COLUMN ENDS-->
					<div class="one-fourth">
						<!-- COLUMN STARTS-->
						<h4><a href="#">Web development</a></h4>
						<p>
							 Lorem ipsum dolor sit amet, tollite fit manibus individuationis omnibus civitas ad quia. Quaere allocutus ait regem ut sua etiam quantitas non solutionem invenisti.
						</p>
					</div>
					<!-- COLUMN ENDS-->
					<div class="one-fourth">
						<!-- COLUMN STARTS-->
						<h4><a href="#">Web Design</a></h4>
						<p>
							 Lorem ipsum dolor sit amet, tollite fit manibus individuationis omnibus civitas ad quia. Quaere allocutus ait regem ut sua etiam quantitas non solutionem invenisti.
						</p>
					</div>
					<!-- COLUMN ENDS-->
					<div class="one-fourth last">
						<!-- COLUMN STARTS-->
						<h4><a href="#">Web Hosting</a></h4>
						<p>
							 Lorem ipsum dolor sit amet, tollite fit manibus individuationis omnibus civitas ad quia. Quaere allocutus ait regem ut sua etiam quantitas non solutionem invenisti.
						</p>

					</div>
					<!-- COLUMN ENDS-->
					<div class="horizontal-line"></div>
				</div>