
<header class="jumbotron subhead" id="overview">
  <div class="inner">
    <div class="container">
      <h1>Administrator Page</h1>
      <p class="lead">
        Gain access to top secret stats and more ...
      </p>
    </div><!-- /container -->
  </div>
</header>

<div class="container" style='padding-top: 40px;'>

	<div class="content">
		<div class="page-header">
		  <h1>Please Proceed to Log-in<small> </small></h1>
		</div>
		<div class="row">
		  <div class="span10">
		    <p>If you are having difficulty, please contact the administrator</p>
		  </div>
		</div>
	</div>
	
</div>