<div class="left" style="width:20%;">

	<div class="content">
	
		<div>
			<h4>Users</h4>
		</div>
		
		<div class="row">
		  <div class="span10">
		  	<ul class="content_menu menu">
		  		<li><a href="#basic_info">Basic user info</a></li>
		  	</ul>
		  	
		  </div>
		</div>
		
	</div>
	
</div>

<div class="left">

	<div class="content">

		<div class="page-header">
		  <h3>
		  	<?php if($this->params('id')){ ?>
		  		Update user
		  	<?php }else { ?>
		  		Add user
		  	<?php } ?>
		  </h3>
		</div>
		
		<div class="row">
		  	<div class="span12">
		  		<form action="/admin/save" method="POST">
		  			<input type="hidden" name="model" value="User">
		  			<input type="hidden" name="id" value="<?php echo $this->params('id'); ?>">
			        <fieldset>
						
			        	<legend><a name="basic_info"></a> Basic info</legend>
			          
			          	<?php 
			          		$scheme = Jien::model("User")->scheme();
			          		foreach($scheme AS $field=>$values){
			          			$label = ucfirst($field);
			          			$type = $values['DATA_TYPE'];
			          			if($field == 'password') $type = 'password';
			          			$value = '';
			          			if($this->data){
			          				$value = $this->data[$field];
			          			}
			          	?>
			          
				          <div class="clearfix">
				            <label for="xlInput"><?php echo $label; ?></label>
				            <div class="input">
				              	<input class="xlarge" name="<?php echo $field; ?>" value="<?php echo $value; ?>" size="30" type="<?php echo $type; ?>">
				            </div>
				          </div><!-- /clearfix -->
			          
			          	 <?php } ?>
			          
			          
			        </fieldset>
			         
			        <fieldset>
			          <div class="actions">
			            <input type="submit" class="btn primary" value="Save changes">&nbsp;<button type="reset" class="btn">Cancel</button>
			          </div>
			        </fieldset>
			      </form>
		  	</div>
		</div>
	
	</div>
	
</div>

