<div class="left" style="width:20%;">

	<div class="content">
	
		<div>
			<h4>Users</h4>
		</div>
		
		<div class="row">
		  <div class="span10">
		  	<ul class="content_menu menu">
		  		<li><a class='active' href="/admin/users">List all users</a></li>
		  		<li><a href="/admin/users/add">Add a new user</a></li>
		  	</ul>
		  	
		  </div>
		</div>
		
	</div>
	
</div>

<div class="left">

	<div class="content">

		<div class="page-header">
		  <h3>
		  	Listing all users <small></small>
		  </h3>
		</div>
		
		<div class="row">
		  	<div class="span12">
		    	<?php echo $this->paginator($this->data, true); ?>
		  	</div>
		</div>
		
		<div class="row">
		  	<div class="span12">
		  	
		  		<table class="zebra-striped" id="sortTableExample">
			        <thead>
			          <tr>
			            <th class="header">#</th>
			            <th class="header">Username</th>
			            <th class="header">Email</th>
			            <th class="header">Role</th>
			            <th class="header">Joined</th>
			            <th class="header">Action</th>
			          </tr>
			        </thead>
			        <tbody>
			        <?php foreach($this->data['records'] AS $key=>$value){ ?>
			        <tr>
			            <td><?php echo $value['user_id']; ?></td>
			            <td><?php echo $value['username']; ?></td>
			            <td><?php echo $value['email']; ?></td>
			            <td><?php echo $value['role']; ?></td>
			            <td><?php echo date("m/d/y", strtotime($value['created'])); ?></td>
			            <td>
			            	<a href="#" class="btn blue">Edit</a>
			            	<a href="#" class="btn red">Delete</a>
			            </td>
			          </tr>
			          <?php } ?>
			          </tbody>
			      </table>
			      
			     <?php echo $this->paginator($this->data); ?>
		  	</div>
		  	
		  	
		  	
		</div>
	
	</div>
	
</div>

