

<div class="left">

	<div class="content">

		<div class="page-header">
			<h3>
		  		Listing all users <small></small> <span class='right'><a href='/admin/user'>Add a user</a></span>
		  	</h3>
		</div>
		
		<div class="row">
		  	<div class="span12">
		    	<?php echo $this->paginator($this->data, true); ?>
		  	</div>
		</div>
		
		<div class="row">
		  	<div class="span15">
		  	
		  		<table class="zebra-striped">
			        <thead>
			          <tr>
			            <th class="header">#</th>
			            <th class="header">Username</th>
			            <th class="header">Email</th>
			            <th class="header">Role</th>
			            <th class="header">Joined</th>
			            <th class="header">Action</th>
			          </tr>
			        </thead>
			        <tbody>
			        <?php foreach($this->data['records'] AS $key=>$value){ ?>
			        <tr>
			            <td><?php echo $value['user_id']; ?></td>
			            <td><?php echo $value['username']; ?></td>
			            <td><?php echo $value['email']; ?></td>
			            <td><?php echo $value['role']; ?></td>
			            <td><?php echo date("m/d/y", strtotime($value['created'])); ?></td>
			            <td>
			            	<a href="/admin/user/id/<?php echo $value['user_id']; ?>" class="btn blue">Edit</a>
			            	<a href="/admin/delete/?model=User&id=<?php echo $value['user_id']; ?>" class="btn red">Remove</a>
			            </td>
			          </tr>
			          <?php } ?>
			          </tbody>
			      </table>
			      
			     <?php echo $this->paginator($this->data); ?>
		  	</div>
		  	
		  	
		  	
		</div>
	
	</div>
	
</div>

